# Generated by Django 5.0.6 on 2026-05-28 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_movie_status_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='timing',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(16, 30), '4:30 PM'), (datetime.time(19, 0), '7:00 PM'), (datetime.time(22, 30), '10:30 PM')]),
        ),
    ]
