# Generated by Django 5.0.6 on 2026-05-29 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_id_alter_movie_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['show_date', 'timing']},
        ),
        migrations.AddField(
            model_name='show',
            name='show_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
